;; Rust
(require 'func-package)

(require-package 'company)
(require-package 'racer)
(require-package 'rust-mode)
(require-package 'electric)
(require-package 'eldoc)
(require-package 'flycheck)
(require-package 'flycheck-rust)
(require-package 'cargo)
(require-package 'yasnippet)

(add-hook 'rust-mode-hook (lambda()
							(require 'company)
							(require 'racer)
							(require 'rust-mode)
							(require 'electric)
							(require 'eldoc)
							(require 'flycheck)
							(require 'flycheck-rust)
							(require 'cargo)
							(require 'yasnippet)
							(setq racer-cmd "~/.cargo/bin/racer")
							(setq racer-rust-src-path (expand-file-name "rust/src"
																		user-emacs-directory))
							(setq rust-format-on-save t)
							(electric-pair-mode 1)
							(company-mode)
							(racer-mode)
							(flycheck-mode)
							(flycheck-rust-setup)
							(cargo-minor-mode)
							(yas-minor-mode)
							(hs-minor-mode)))

;; Provide
(provide 'sup-rust)
